# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- script: dotnet build ./AkkaIoTIngress/ --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- script: dotnet publish ./AkkaIoTIngress/ --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: ./AkkaIoTIngress/bin/$(buildConfiguration)/netcoreapp2.0
    artifactName: akkaiot
